version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-tag-1.37.19-64bit
    steps:
      - checkout
      - run: git submodule update --init
      - run: |
          . /entrypoint
          echo $PATH
          echo $EMSCRIPTEN
          scripts/travis-emscripten/install_deps.sh
      - run: |
          . /entrypoint
          scripts/travis-emscripten/build_emscripten.sh

      - run:
          name: Build
          command: |
            . /entrypoint
            WORKSPACE=$(pwd)
            mkdir -p build
            cd build
            cmake \
              -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DEMSCRIPTEN=1 \
              -DBoost_FOUND=1 \
              -DBoost_USE_STATIC_LIBS=1 \
              -DBoost_USE_STATIC_RUNTIME=1 \
              -DBoost_INCLUDE_DIR="$WORKSPACE"/boost_1_57_0/ \
              -DBoost_CHRONO_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_chrono.a \
              -DBoost_CHRONO_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_chrono.a \
              -DBoost_DATE_TIME_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_date_time.a \
              -DBoost_DATE_TIME_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_date_time.a \
              -DBoost_FILESYSTEM_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_filesystem.a \
              -DBoost_FILESYSTEM_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_filesystem.a \
              -DBoost_PROGRAM_OPTIONS_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_program_options.a \
              -DBoost_PROGRAM_OPTIONS_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_program_options.a \
              -DBoost_RANDOM_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_random.a \
              -DBoost_RANDOM_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_random.a \
              -DBoost_REGEX_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_regex.a \
              -DBoost_REGEX_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_regex.a \
              -DBoost_SYSTEM_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_system.a \
              -DBoost_SYSTEM_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_system.a \
              -DBoost_THREAD_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_thread.a \
              -DBoost_THREAD_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_thread.a \
              -DBoost_UNIT_TEST_FRAMEWORK_LIBRARY="$WORKSPACE"/boost_1_57_0/libboost_unit_test_framework.a \
              -DBoost_UNIT_TEST_FRAMEWORK_LIBRARIES="$WORKSPACE"/boost_1_57_0/libboost_unit_test_framework.a \
              -DDev_DEVCORE_LIBRARY="$WORKSPACE"/solidity/build/libdevcore/libsoldevcore.a \
              -DEth_EVMASM_LIBRARY="$WORKSPACE"/solidity/build/libevmasm/libsolevmasm.a \
              -DETH_STATIC=1 -DTESTS=0 \
              ..
            make -j 4

            cd ..
            cp build/solc/soljson.js ./
            mkdir -p upload
            cp soljson.js upload/

            OUTPUT_SIZE=`ls -la build/solc/soljson.js`

            echo "Emscripten output size: $OUTPUT_SIZE"